name: dgraphfin_ER_BSL

dataset:
  root: "data/dgraphfin"

model:
  hidden_dim: 96
  output_dim: 1
  dropout: 0.5
  num_heads: 4
  num_layers: 2

train:
  dataset: dgraphfin
  model: bsl
  device: cuda
  lr: 0.001
  weight_decay: 1e-5
  print_freq: 10
  save_dir: weights/bsl/dgraphfin_ER_BSL

  num_epochs_per_task: 30
  task_schedule:
    - [0]
    - [1]
    - [2]
    - [3]
    - [4]
    - [5]
    - [6]
    - [7]
    - [8]
    - [9]

  ewc_lambda: 0.0
  spc_lambda: 0.0
  scd_lambda: 0.0
  lwf_alpha: 0.0
  lwf_temperature: 1.0
  buffer_size_per_class: 100
  threshold: 0.5
